### ISSUE TITLE
能给css写点注释么？也让我们理解下代码里面的原理或者为什么这样做！！！

### ISSUE THREAD

**Issue by codekissyoung** [BoizZ/native-reset.css#1]

**Comment by codekissyoung** [comment]
这样也许会有更多的交流！

**Comment by boizz** [comment]
其实大多数都是为了统一各个浏览器的样式，但是 `1.2.2` 版本包含了一些个性化特性，例如 `list-style`、各个 `block` 元素的 `padding` 和 `magin` 等，这些特性可能不是所有人都喜欢的，基于此，这里用 `sass` 写了新的版本，更方便管理自定义特性。
